Repository TerraMours/TerraMours_Admin_Web, pull requests merged in 2023-09, with the labels that each got.

#5 fix(components): 列表在新增修改后的刷新操作，获取最新的数据
  src/views/management/category/components/table-action-modal.vue
  src/views/management/category/index.vue
  src/views/management/chat/index.vue
  src/views/management/keyOption/components/table-action-modal.vue
  src/views/management/keyOption/index.vue
  src/views/management/product/components/table-action-modal.vue
  src/views/management/product/index.vue
  src/views/management/promptOption/components/table-action-modal.vue
  src/views/management/promptOption/index.vue
  src/views/management/role/components/table-action-modal.vue
  src/views/management/role/index.vue
  src/views/management/route/components/table-action-modal.vue
  src/views/management/route/index.vue
  src/views/management/sensitive/components/table-action-modal.vue
  src/views/management/sensitive/index.vue
  src/views/management/user/components/table-action-modal.vue
  src/views/management/user/index.vue
Labels: bug

#9 feat(components): 去除默认密码
  src/views/_builtin/login/components/pwd-login/index.vue
Labels: documentation

#11 feat(projects): 列表查询中添加用户名称字段
  src/layouts/common/global-header/components/github-site.vue
  src/typings/api.d.ts
  src/views/about/components/project-info.vue
  src/views/component/button/index.vue
  src/views/component/table/index.vue
  src/views/management/category/index.vue
  src/views/management/chat/index.vue
  src/views/management/image/index.vue
  src/views/management/order/index.vue
  src/views/management/product/index.vue
  src/views/management/role/index.vue
  src/views/management/route/index.vue
  src/views/management/user/index.vue
Labels: enhancement

#12 feat(projects): 1.pinia版本兼容2.手机端兼容3.添加获取docker环境变量代码。
  package.json
  src/composables/layout.ts
  src/layouts/basic-layout/index.vue
  src/service/request/index.ts
Labels: enhancement
